[[change]]
offset = 0x36c
old = [0x10,0x10]
new = [0x10,0x08]
func = "main"
comment = "text_draw_xy_step , dividing by x by 2"

[[change]]
offset = 0x2da2
old = [0x81,0x93]
new = [0x81,0x65]
func = "MES_execute"
comment = "change CR code from sjis % to ascii %"

[[change]]
offset = 0x36ce
old = [0x40,0x0b]
new = [0x00,0x09]
func = "MES_execute"
comment = "skip font loading command in the script"

[[change]]
offset = 0x3fd
old = [0x20,0x20]
new = [0x22,0x80]
func = "MES_execute"
comment = "shifting font from 0x00202000 to 0x00228000"

[[change]]
offset = 0x51d
old = [0x20,0x20]
new = [0x22,0x80]
func = "MES_execute"
comment = "shifting font from 0x00202000 to 0x00228000"

[[change]]
offset = 0x37ed
old = [0x20,0x20]
new = [0x22,0x80]
func = "MES_execute"
comment = "shifting font from 0x00202000 to 0x00228000"

[[change]]
offset = 0x5329
old = [0x20,0x20]
new = [0x22,0x80]
func = "MES_execute"
comment = "shifting font from 0x00202000 to 0x00228000"

[[change]]
offset = 0x5461
old = [0x20,0x20]
new = [0x22,0x80]
func = "MES_execute"
comment = "shifting font from 0x00202000 to 0x00228000"
